
//**********************************************************************//
void uDelay(long l);
void kDelay(unsigned char n);
void Delay(unsigned char n);
void mDelay(char time);
void Write_Command(unsigned char Data);
void Write_Data(unsigned char Data);
void Set_Column_Address(unsigned char a, unsigned char b);
void Set_Row_Address(unsigned char a, unsigned char b);
void Set_Write_RAM();
void Set_Read_RAM();
void Set_Remap_Format(unsigned char d);
void Set_Start_Line(unsigned char d);
void Set_Display_Offset(unsigned char d);
void Set_Display_Mode(unsigned char d);
void Set_Function_Selection(unsigned char d);
void Set_Display_On_Off(unsigned char d);
void Set_Phase_Length(unsigned char d);
void Set_Display_Enhancement(unsigned char d);
void Set_Display_Enhancement(unsigned char d);
void Set_Display_Clock(unsigned char d);
void Set_VSL(unsigned char d);
void Set_GPIO(unsigned char d);
void Set_Precharge_Period(unsigned char d);
void Set_Precharge_Voltage(unsigned char d);
void Set_VCOMH(unsigned char d);
void Set_Contrast_Color(unsigned char a, unsigned char b, unsigned char c);
void Set_Master_Current(unsigned char d);
void Set_Multiplex_Ratio(unsigned char d);
void Set_Command_Lock(unsigned char d);
void Fill_RAM(int Colour_RGB);
void Fill_Block(unsigned char a, unsigned char b, unsigned char c, unsigned char d, unsigned char e, unsigned char f);
void Rainbow();
void Vertical_Scroll(unsigned char a, unsigned char b, unsigned char c);
void Horizontal_Scroll(unsigned char a, unsigned char b, unsigned char c, unsigned char d, unsigned char e, unsigned char f);
void Deactivate_Scroll();
void Fade_In(bit time_mode,char time);
void Fade_Out(bit time_mode,char time);
void Sleep(unsigned char a);
void Set_Gray_Scale_Table();
void Set_Linear_Gray_Scale_Table();
void OLED_Init();
void Draw_Rectangle(unsigned char a, unsigned char b, unsigned char c, unsigned char d, unsigned char e, int Colour_RGB);
void Draw_Point(unsigned char x, unsigned char y, int Colour_RGB);
void Draw_Circle(char x0,char y0,char r,int colour,char time,bit time_mode);
void Draw_Line(int x1,int y1,int x2,int y2,int color);
void Draw_Triangle(int x,int y,int r,int color);
void Display_Pattern(unsigned char *Pattern_Data, unsigned char Start_x, unsigned char End_x, unsigned char Start_y, unsigned char End_y);
void Display_Char(unsigned char x, unsigned char y, unsigned char Var_Char, int Colour_RGB);
void Display_String(unsigned char x, unsigned char y, unsigned char *chr, int Colour_RGB);
void Fill_Circle(char x0,char y0,char r,int colour);